### ISSUE TITLE
配置文件，可以按照目录加载么？

### ISSUE THREAD

**Issue by SoberChina** [JeffLi1993/springboot-learning-example#12]
您好：
     我的项目比较老，引用其他组的jar包，文件名称算是写死的吧，springBoot 可以修改CLASSPATH么？直接指定文件夹？ 谢谢

**Comment by JeffLi1993** [comment]
可以看我这篇文章 http://gitbook.cn/gitchat/activity/5a69a12f0b172b546f92f26c
