### ISSUE TITLE
很感谢本教程, 想了解一下多模块下无法扫描到dao模块下mapper 该如何设置呢?

### ISSUE THREAD

**Issue by evanyangg** [JeffLi1993/springboot-learning-example#16]
![image](https://user-images.githubusercontent.com/22952321/28765583-226cc868-7591-11e7-8b7b-10cd492511c1.png)
这是dao层,
现在我在server层启动已用,
出现这个错误
![image](https://user-images.githubusercontent.com/22952321/28765601-3b9c4b6a-7591-11e7-8fe0-277940e1fda0.png)
大概是哪里出了问题呢?

**Comment by JeffLi1993** [comment]
路径配错了
