### ISSUE TITLE
Could not autowire. No beans of 'CityDao' type found.

### ISSUE THREAD

**Issue by blue-troy** [JeffLi1993/springboot-learning-example#3]
你好，我clone了你的项目，发现在idea下 package org.spring.springboot.service.impl 中的 @Autowired
    private CityDao cityDao;
出现了Could not autowire. No beans of 'CityDao' type found. 提示，不知是什么原因。

**Comment by JeffLi1993** [comment]
which 子工程？

**Comment by blue-troy** [comment]
springboot-learning-example/springboot-mybatis/

**Comment by JeffLi1993** [comment]
mvn clean install -U .估计没打包好

**Comment by squallssck** [comment]
是ideal的问题,运行是没有问题的. 但是就是会有红线提示比较讨厌.

**Comment by squallssck** [comment]
http://www.cnblogs.com/zhangdong92/p/6986653.html
可以看下这里的一个解决方法

**Comment by hbbliyong** [comment]
你的解决了吗，我也是这个问题，如果解决请告知

**Comment by adonis-lau** [comment]
感觉是up代码写的有些问题。
在CityDao类加上@Repository就好了。

**Comment by zhonghuazhi** [comment]
我这边运行 执行报错，提示如下：
Description:

Field cityDao in net.cc.restful.service.impl.CityServiceImpl required a bean of type 'net.cc.restful.dao.CityDao' that could not be found.


Action:

Consider defining a bean of type 'net.cc.restful.dao.CityDao' in your configuration.

**Comment by JeffLi1993** [comment]
fix

**Comment by Applevegetable** [comment]
dao层加@Repository

**Comment by GitHubXuMing** [comment]
邮件已收到祝好                        徐铭

**Comment by chenzl0723** [comment]
已收到 ，谢谢

**Comment by VitorTao** [comment]
来信已收到，非常感谢

**Comment by Jokeridea** [comment]
这是来自QQ邮箱的假期自动回复邮件。王绅杰 收到，谢谢~

**Comment by chenzl0723** [comment]
已收到 ，谢谢

**Comment by VitorTao** [comment]
来信已收到，非常感谢
