### ISSUE TITLE
springBoot+dubbo 消费者 怎么添加 热部署

### ISSUE THREAD

**Issue by songjinglei** [JeffLi1993/springboot-learning-example#31]
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
 </dependency>
如果没有热部署   重启 岂不是很频繁
引如 这个 jar 后 消费者服务 ，启动报错    is not visible from class loader
我  问 度娘    解释说 是    加载bean 的顺序 有问题   @Reference 注入  为 null   
请教 有什么好的方式 解决这个问题 木有

**Comment by liu-mw** [comment]
热部署方式不是有三种吗，博主用devtools就是其中一种
