### ISSUE TITLE
redis issue

### ISSUE THREAD

**Issue by zhangliting** [JeffLi1993/springboot-learning-example#54]
几个关于redis的例子有问题，@Cacheable没有使用redis，只在application.properties里面配置redis是没有用的，默认使用的是ConcurrentHashMap作为缓存。

**Comment by yuFFF** [comment]
依赖的包有问题：
spring-boot-starter-redis
应该改成
spring-boot-starter-data-redis

**Comment by neilgamer** [comment]
楼上正解
