### ISSUE TITLE
外部tomcat拦截器生效

### ISSUE THREAD

**Issue by MrZhangDemo** [JeffLi1993/springboot-learning-example#74]
您好，请问下springboot项目在内置tomcat中启动，拦截器可以生效，打包成war部署到外部tomcat拦截器就失效了呢

**Comment by JeffLi1993** [comment]
不需要打 war 包，启动。启动看这篇文章：

https://www.bysocket.com/archives/2119

也可以使用 Spring Boot 开发传统的应用，只要通过 Spring Boot Maven 插件将 Jar 应用转换成 War 应用即可。
